language: node_js
node_js:
  - "lts/*"
jobs:
  include:
    - stage: test
      script: CI=true yarn test --env=jsdom
    - stage: build
      script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: false
  local-dir: build
  email: no@email.com
  name: Travis
  on:
    branch: master
